-- Epic Clarity Database Schema for PostgreSQL

-- Patient Table
CREATE TABLE PATIENT (
    PAT_ID SERIAL PRIMARY KEY,
    PAT_MRN_ID VARCHAR(50) NOT NULL,
    PAT_FIRST_NAME VARCHAR(100),
    PAT_LAST_NAME VARCHAR(100),
    BIRTH_DATE DATE,
    DEATH_DATE DATE,
    SEX_C CHAR(1),
    ETHNIC_GROUP_C VARCHAR(50),
    PATIENT_RACE_C VARCHAR(50),
    PRIMARY_LANGUAGE_C VARCHAR(50),
    MARITAL_STATUS_C VARCHAR(50),
    ZIP VARCHAR(20),
    CITY VARCHAR(100),
    STATE_C CHAR(2),
    COUNTRY_C VARCHAR(100),
    EMAIL_ADDRESS VARCHAR(255),
    HOME_PHONE VARCHAR(20),
    WORK_PHONE VARCHAR(20),
    MOBILE_PHONE VARCHAR(20),
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);

-- Encounter Table
CREATE TABLE PAT_ENC (
    ENCOUNTER_ID SERIAL PRIMARY KEY,
    PAT_ID INT REFERENCES PATIENT(PAT_ID),
    ENCOUNTER_DATE TIMESTAMP,
    ENCOUNTER_TYPE VARCHAR(50),
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);

-- Diagnoses Table
CREATE TABLE CLARITY_EDG (
    DIAGNOSIS_ID SERIAL PRIMARY KEY,
    PAT_ID INT REFERENCES PATIENT(PAT_ID),
    ICD10_CODE VARCHAR(10),
    DIAGNOSIS_DATE DATE,
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);

-- Procedures Table
CREATE TABLE CLARITY_EAP (
    PROCEDURE_ID SERIAL PRIMARY KEY,
    PAT_ID INT REFERENCES PATIENT(PAT_ID),
    CPT_CODE VARCHAR(10),
    PROCEDURE_DATE DATE,
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);

-- Lab Results Table
CREATE TABLE LAB_RESULTS (
    RESULT_ID SERIAL PRIMARY KEY,
    PAT_ID INT REFERENCES PATIENT(PAT_ID),
    LOINC_CODE VARCHAR(10),
    RESULT_VALUE VARCHAR(100),
    RESULT_DATE DATE,
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);

-- Medications Table
CREATE TABLE MEDICATIONS (
    MEDICATION_ID SERIAL PRIMARY KEY,
    PAT_ID INT REFERENCES PATIENT(PAT_ID),
    RXNORM_CODE VARCHAR(20),
    MEDICATION_NAME VARCHAR(255),
    DOSAGE VARCHAR(50),
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);

-- Clinical Notes Table
CREATE TABLE HNO_INFO (
    NOTE_ID SERIAL PRIMARY KEY,
    PAT_ID INT REFERENCES PATIENT(PAT_ID),
    NOTE_TEXT TEXT,
    NOTE_DATE DATE,
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);

-- Providers Table
CREATE TABLE PROVIDERS (
    PROVIDER_ID SERIAL PRIMARY KEY,
    PROVIDER_NAME VARCHAR(255),
    SPECIALTY VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);

-- Departments Table
CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID SERIAL PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(255),
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);

-- Vocabulary Reference Tables
CREATE TABLE ICD10_CODES (
    CODE_ID SERIAL PRIMARY KEY,
    CODE VARCHAR(10) UNIQUE,
    DESCRIPTION TEXT,
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);

CREATE TABLE CPT_CODES (
    CODE_ID SERIAL PRIMARY KEY,
    CODE VARCHAR(10) UNIQUE,
    DESCRIPTION TEXT,
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);

CREATE TABLE SNOMED_CONCEPTS (
    CONCEPT_ID SERIAL PRIMARY KEY,
    CODE VARCHAR(50) UNIQUE,
    DESCRIPTION TEXT,
    CREATED_DATE TIMESTAMP DEFAULT NOW(),
    UPDATED_DATE TIMESTAMP DEFAULT NOW()
);